### ISSUE TITLE
Reviving a player with lots of enemy corpses nearby or above the teammate corpse, will stop the action of reviving the player

### ISSUE THREAD

**Issue by eflernicolas** [AoiKagase/Amxx-ReviveKit#4]
most of the times there is a pile of corpses blocking the revive for the opposite team.

**Comment by AoiKagase** [comment]
I am aware of the problem, but it needs to be investigated.
Please wait a while for other issues to be included.

**Comment by eflernicolas** [comment]
> I am aware of the problem, but it needs to be investigated. Please wait a while for other issues to be included.

Thank you!

**Comment by eflernicolas** [comment]
> I am aware of the problem, but it needs to be investigated. Please wait a while for other issues to be included.

replying here to not create that many issues.

getting this in server console "SV_StartSound: items/smallmedkit2.wav not precached (0)"

**Comment by AoiKagase** [comment]
There is an original process to check for obstacles when getting the ID of a corpse.
I modified this to ignore corpses, but the test is insufficient.
The Precache error has been fixed.

**Comment by eflernicolas** [comment]
> There is an original process to check for obstacles when getting the ID of a corpse. I modified this to ignore corpses, but the test is insufficient. The Precache error has been fixed.

Test being insufficient meaning that is still not fixed?
thanks for the precache error fix!

i would not have a problem with the obstacle function being removed, if its easier for it to work better. 
I dont think it ruins the immersion

**Comment by eflernicolas** [comment]
can we make a cvar for the obstacle function to be removed? so i can remove freely even with lots of corpses? i will consider this as a fix.
